### PR TITLE
Allow client options to be passed into Jasmine

### PR DESCRIPTION
**Pull request by jsilvestri**
This addresses https://github.com/jejacks0n/teaspoon/issues/518. Example usage in teaspoon_env.rb:

```
client = Selenium::WebDriver::Remote::Http::Default.new
client.timeout = 180 # 3 mins instead of the default 60 seconds
config.driver_options = {client_driver: :firefox, client_driver_opts: {http_client: client}}
```

### CODE REVIEW

**Comment by jsilvestri** [comment]
I am not quite sure I understand what is failing in the tests...

**Comment by CyborgMaster** [comment]
I would love to get this merged.  We also would like to pass client options.  In this case, ours is to use chrome headless to run the tests using something like this:
```
  options = ::Selenium::WebDriver::Chrome::Options.new
  options.add_argument('--headless')
  options.add_argument('--disable-gpu')
  config.driver_options = { client_driver: :chrome, client_driver_ops: { options: options } }
```

**Comment by tilsammans** [comment]
@CyborgMaster I would just open a new PR that contains all the needed changes.

Then we can get some movement on this issue! If you need help with anything, don't be shy.

**Comment by jejacks0n** [comment]
I'm a little lost -- can someone explain like I'm 5? I'm slammed at work, so if you just give me a clean PR with an explanation and reasonable certainty that it takes everything needed into account I'll merge it.

**Comment by tilsammans** [comment]
#530 opened which contains all the fixes.

**Comment by tilsammans** [comment]
@jsilvestri @jejacks0n pull requests are all failing now because of CodeClimate changes. Can you or anyone look into this? I'd like to get #530 merged soon as I have fixes waiting for them downstream.

**Comment by zzak** [comment]
@tilsammans I'm trying to fix the Code Climate situation here in #534

**Comment by zzak** [comment]
Hello ya'll, #534 fixes the build so once that's merged we can hopefully push this forward. I'd like to see people be able to use `teaspoon` with headless chrome :)

Happy Holidays!

**Comment by jejacks0n** [comment]
There's several PRs that are linking to Other PRs.. I've merged the one that fixed the build.. what's the status of other ones?

**Comment by tilsammans** [comment]
In principle #530 contains the fixed code, but tests are now failing because the method signature changed.

I don't have time in the coming weeks to install `qmake` locally. It's such a pain to do.

**Comment by zzak** [comment]
@tilsammans I can't tell the difference, maybe you can rebase?

**Comment by tilsammans** [comment]
@zzak this one—#519—isn't mine. #530 I rebased already.

**Comment by zzak** [comment]
@tilsammans Yep, I've seen both but I'm clearly not in a place to tell which patch is best -- my suggestion is to rebase so the tests pass and / or explain how they defer. It's very likely someone with more context (i.e. the maintainer) can tell the difference but all your PR proclaims is that it "continues" this PR. How about elaborating on why your patch should be merged instead of this? What does it improve or how does it differ? Adding as much context as possible will help you get your patches merged in an ad-hoc open-source project such as this.

**Comment by tilsammans** [comment]
@zzak allright: my pull request #530 contains the changes proposed by @CyborgMaster which duplicates the options. He never submitted a pull request so I did that.

The tests are currently failing because the signature of the method changed. (both here and in my PR). Since I don't have `qmake` nor do I have 6 hours to spare to install it. that's where we all stand.

**Comment by mathias** [comment]
I've been trying to get this working by using the branch, but every time, I get
```Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515```
locally.

This works on Travis. Chromedriver is working for the Capybara Rails tests. Any ideas why I get that?

**Comment by mathias** [comment]
@jejacks0n I've got that (Capybara on Rails suite is using it) and tried updating it, but haven't gotten this working locally. Oddly, it works on Travis using the exact same config.

**Comment by trcarden** [comment]
Since I arrived here trying to get chrome headless working and concluded from this PR originally that this project was not being maintained and chrome headless was not being worked on I thought I would share this update:

I noticed that another PR was merged to support selenium options on master via: https://github.com/jejacks0n/teaspoon/pull/537

I am going to try and help @jejacks0n a little here:

- I have updated the wiki with a small note here: https://github.com/jejacks0n/teaspoon/wiki/Using-Selenium-WebDriver
- I think the following can be closed:
  - https://github.com/jejacks0n/teaspoon/pull/519 - (this PR) unless @jsilvestri objects
  - https://github.com/jejacks0n/teaspoon/issues/518 - the issue for this PR 
  - https://github.com/jejacks0n/teaspoon/pull/530 - (another PR trying to do the same)
- A friendly shoutout around https://github.com/solidusio/solidus/pull/2534 as the monkey patch might not be required anymore (or if all the waiting is might be something the mainline might benefit from)

It should would be great if we could get a new gem cut too.

**Comment by mathieujobin** [comment]
looks like #537 properly fix this issue, please reopen if you disagree

**Pull request closed without merging**
