### PR TITLE
Support for webpacker

### PR DESCRIPTION
**Pull request by mfazekas**
Rails 5.1 will introduce webpacker see https://github.com/rails/webpacker.

The ideas is that it allows assets to be compiled by webpacker, but those have to be include by adding `javascript_pack_tag`

### CODE REVIEW

**Comment by mfazekas** [comment]
@jejacks0n any feedback on this?

I've tried to fix travis, some fixed clode climate codecov and installed geckodriver, but now i'm getting ` Selenium::WebDriver::Error::ServerError: status code 500` on travis, but work locally.

**Comment by mfazekas** [comment]
@jejacks0n ping, rails 5.1 is out now

**Comment by mfazekas** [comment]
@jejacks0n any update on this?

**Comment by jejacks0n** [comment]
Alright, I tried to get this merged, but it's complicated and stale. I'm going to take what you've done here and commit it.. sorry!

**Comment by jejacks0n** [comment]
The code climate adjustments are where I had the most trouble. I know you were trying to be kind with that effort. =)

**Comment by mfazekas** [comment]
@jejacks0n no worries i'll try to rebase it.

**Comment by mfazekas** [comment]
@jejacks0n i've removed code climate changes. Only the ruby 2.5/rails 6 passes now. 

Rails 5 test fails with ```You requested coverage reports, but no results were found. Are all files being ignored in your coverage config? If you have expand_assets set to false, you will need to remove spec_helper from the ignore list.```

Do you have tips for that?

**Comment by mathieujobin** [comment]
rebased into `e1c9097`

anyone would wish to see this change being merged? please vote in

**Pull request merged**
